### ISSUE TITLE
setTitleWidth、setTitleHeight里面的参数值单位好像不是dp吧？

### ISSUE THREAD

**Issue by cfzy** [z3896823/PanelList#13]
setTitle("序号")
setTitleWidth(80)、setTitleHeight(80)
在低分辨率设备上“序号”两字还能看见，在华为P8的1920*1080分辨率上只能显示1个字。
是不是里面单位不是dp？

**Comment by z3896823** [comment]
对的，之前是 px 来着，现在已经改为 dp 啦~
