### ISSUE TITLE
1.2.1的版本安装不上，1.2.0的可以

### ISSUE THREAD

**Issue by bojectss501** [z3896823/PanelList#5]
我AS3.0版本

**Comment by bojectss501** [comment]
![image](https://user-images.githubusercontent.com/7599070/32886997-6f063d3c-cafd-11e7-9912-c78f232b2932.png)

**Comment by blueskyfred1** [comment]
the same question

**Comment by z3896823** [comment]
非常抱歉，v1.2.1在更新的时候使用了3.0的AS，它提示我使用新版本的gradle，结果我更新了gradle（4.1）后jitpack始终无法生成链接。看了下build.log，似乎是jitpack无法下载4.1的gradle，强行将项目的gradle降到3.3后，发现如果使用原来的版本号还是无法生成连接，似乎jitpack缓存了之前版本的信息，使用新版本号后问题解决，现在请使用gradle compile新的版本号就可以了，我这边测试没问题
compile 'com.github.z3896823:PanelList:v1.2.3'
