### ISSUE TITLE
表头布局ll_row和lv_column设置Divider无效

### ISSUE THREAD

**Issue by monkey008** [z3896823/PanelList#6]
ll_row设置Divider无效的原因是：
LinearLayout单独调用setDividerDrawable(rowDivider);是无效的，还应该调用setShowDividers(SHOW_DIVIDER_END|SHOW_DIVIDER_MIDDLE|SHOW_DIVIDER_BEGINNING);设置显示位置

lv_column设置Divider无效的原因是:
ListView的setDivider(Drawable divider)方法中判断如果divider没有设置高度则会初始化高度为-1，即不显示，所以如果你的shape文件未设置height属性 setDivider是不会起作用的

**Comment by z3896823** [comment]
谢谢提醒，已经修改，下一版中更新。
